# -*- coding: utf-8 -*-
"""mentalhealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fYo-5Vns3fNQl6QUIxAPGx3UkbH9XP8

### ** ARQUIVO MENTAL HEALTH**
"""

import gdown

# URL do Google Drive convertida para download direto
url = 'https://drive.google.com/uc?id=1jw0Uoy1OKzCTBMTB_ELknAIn0dYRgoXM'

# Caminho local para salvar o arquivo .db
output_path = 'mental.db'

# Baixar o arquivo
gdown.download(url, output_path, quiet=False)

"""### **CONEXÃO COM O SQLITE**::"""

import sqlite3

connection = sqlite3.connect('mental.db')

import pandas as pd

data = pd.read_sql_query("select * from sqlite_master where type='table'", connection)

data

pd.read_sql("select * from Answer", connection)

pd.read_sql("select * from Question", connection)

pd.read_sql("select * from Survey", connection)

"""## **ANÁLISE EXPLORATÓRIA**"""

data.isnull().sum()

data.isna().sum()

data.duplicated().sum()

"""data"""

data.info()

"""### **SEPARAÇÃO DAS VARIÁVEIS**"""

nums = ['rootpage']

categ = ['type', 'name', 'tbl_name', 'sql']

"""### **DESCRIÇÃO DAS VARIÁVEIS**"""

data[nums].describe()

for coluna in categ:
   print(f"Contagem de valores para {coluna}:")
   print(data[coluna].value_counts())
   print("\n")